### ISSUE TITLE
readme in home?

### ISSUE THREAD

**Issue by hedefalk** [skx/dotfiles#1]
Just a question? To have a redme on your bare repo, did you have to bloat your $HOME with the readme file? I can't seem to find a way for alternative readme location, other than root...

**Comment by skx** [comment]
Yes I do have `~/README.md`, and yes it annoys me too.  But I figure the benefit of documenting _this_ repository makes it worthwhile.

On my main host I just `rm` it, such that it always shows as deleted.  That gives me the best of both worlds.

**Comment by hedefalk** [comment]
Cool, thanks for info! Yes, I figured. Maybe github/gitlab could support a
setting for an alternative readme location so you can say
dotfiles/README.md and leave it in the actual bare repo or something like
that…

**Comment by hedefalk** [comment]
Cool, thanks for info! Yes, I figured. Maybe github/gitlab could support a setting for an alternative readme location so you can say dotfiles/README.md and leave it in the actual bare repo or something like that…
